alias ls='ls --color=auto'
alias dbreload='rake db:drop --trace; rake db:schema:load --trace; rake db:seed --trace'
alias diff='colordiff'
alias grep='grep --color=auto'
alias hibernate='sudo pm-hibernate'
alias appleterm='/usr/lib/xscreensaver/apple2 -text -fast -program 'bash' -geom =1020x580'
alias poweroff='sudo poweroff'
alias python-server='python2 -m SimpleHTTPServer'
# Initialise ESI Maya 44 USB
alias maya44usbjackd='jackd -R -d alsa -d hw:1 -s -r 44100 -X seq'
alias ..='cd ..'
